# config.yaml

artifacts_root: artifact

database:
  database_name: us_visa
  collection_name: visa_data

pipeline:
  pipeline_name: usvisa
  artifact_dir: artifact

files:
  file_name: usvisa.csv
  train_file_name: train.csv
  test_file_name: test.csv
  model_file_name: model.pkl
  preprocessing_object_file_name: preprocessing.pkl
  schema_file_path: config/schema.yaml
  target_column: case_status
  current_year: 2025  # You can dynamically replace this with date.today().year in Python if needed

data_ingestion:
  collection_name: visa_data
  data_ingestion_dir_name: data_ingestion
  data_ingestion_feature_store_dir: feature_store
  data_ingestion_ingested_dir: ingested
  data_ingestion_train_test_split_ratio: 0.25

# data validation related constants
data_validation:
  data_validation_dir_name: "data_validation"
  data_validation_drift_report_dir: "drift_report"
  data_validation_drift_report_file_name: "report.yaml"


# data transformation related constants
data_transformation:
  data_transformation_dir_name: "data_transformation"
  data_transformation_transformed_data_dir: "transformed"
  data_transformation_transformed_object_dir: "transformed_object"
